# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ibex < Formula
  desc "An iOS Backup Extraction Tool"
  homepage "https://github.com/initz3r0/ibex"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/initz3r0/ibex/releases/download/v0.1.0/ibex_0.1.0_darwin_amd64.tar.gz"
      sha256 "44df9c02e90589c9abee821d77ea4b4801d79f8a938c9c7953c360768e4ffd8a"

      def install
        bin.install "ibex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/initz3r0/ibex/releases/download/v0.1.0/ibex_0.1.0_darwin_arm64.tar.gz"
      sha256 "069174f90f7713257ab26330780c7e9435d8a37832b0114bfe7dd2ed1b0796c1"

      def install
        bin.install "ibex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/initz3r0/ibex/releases/download/v0.1.0/ibex_0.1.0_linux_amd64.tar.gz"
        sha256 "cb96e2e9450b163036c65dafb5014419efb6d86a4cd49287a5143e226c7ea9bc"

        def install
          bin.install "ibex"
        end
      end
    end
  end

  test do
    system "#{bin}/ibex --help"
  end
end
